# Warning: SAIF file '/home/syq/spcal/src/spcal/tools/../../../data/saif/arbiter.saif' not found. Init as 0.5.
libs:
- asap7sc7p5t_SIMPLE_RVT_TT_nldm_211120
- asap7sc7p5t_AO_RVT_TT_nldm_211120
- asap7sc7p5t_INVBUF_RVT_TT_nldm_220122
- asap7sc7p5t_OA_RVT_TT_nldm_211120
- asap7sc7p5t_SEQ_RVT_TT_nldm_220123
- manual
port_prefixes:
  input:
  - .A
  - .B
  - .C
  - .D
  - .E
  - .CI
  - .H
  output:
  - .Y
  - .QN
  - .L
  - .SN
  - .CON
external_sp_inputs_spec:
  priority_0_: 0.5
  priority_1_: 0.5
  priority_2_: 0.5
  priority_3_: 0.5
  priority_4_: 0.5
  priority_5_: 0.5
  priority_6_: 0.5
  priority_7_: 0.5
  priority_8_: 0.5
  priority_9_: 0.5
  priority_10_: 0.5
  priority_11_: 0.5
  priority_12_: 0.5
  priority_13_: 0.5
  priority_14_: 0.5
  priority_15_: 0.5
  priority_16_: 0.5
  priority_17_: 0.5
  priority_18_: 0.5
  priority_19_: 0.5
  priority_20_: 0.5
  priority_21_: 0.5
  priority_22_: 0.5
  priority_23_: 0.5
  priority_24_: 0.5
  priority_25_: 0.5
  priority_26_: 0.5
  priority_27_: 0.5
  priority_28_: 0.5
  priority_29_: 0.5
  priority_30_: 0.5
  priority_31_: 0.5
  priority_32_: 0.5
  priority_33_: 0.5
  priority_34_: 0.5
  priority_35_: 0.5
  priority_36_: 0.5
  priority_37_: 0.5
  priority_38_: 0.5
  priority_39_: 0.5
  priority_40_: 0.5
  priority_41_: 0.5
  priority_42_: 0.5
  priority_43_: 0.5
  priority_44_: 0.5
  priority_45_: 0.5
  priority_46_: 0.5
  priority_47_: 0.5
  priority_48_: 0.5
  priority_49_: 0.5
  priority_50_: 0.5
  priority_51_: 0.5
  priority_52_: 0.5
  priority_53_: 0.5
  priority_54_: 0.5
  priority_55_: 0.5
  priority_56_: 0.5
  priority_57_: 0.5
  priority_58_: 0.5
  priority_59_: 0.5
  priority_60_: 0.5
  priority_61_: 0.5
  priority_62_: 0.5
  priority_63_: 0.5
  priority_64_: 0.5
  priority_65_: 0.5
  priority_66_: 0.5
  priority_67_: 0.5
  priority_68_: 0.5
  priority_69_: 0.5
  priority_70_: 0.5
  priority_71_: 0.5
  priority_72_: 0.5
  priority_73_: 0.5
  priority_74_: 0.5
  priority_75_: 0.5
  priority_76_: 0.5
  priority_77_: 0.5
  priority_78_: 0.5
  priority_79_: 0.5
  priority_80_: 0.5
  priority_81_: 0.5
  priority_82_: 0.5
  priority_83_: 0.5
  priority_84_: 0.5
  priority_85_: 0.5
  priority_86_: 0.5
  priority_87_: 0.5
  priority_88_: 0.5
  priority_89_: 0.5
  priority_90_: 0.5
  priority_91_: 0.5
  priority_92_: 0.5
  priority_93_: 0.5
  priority_94_: 0.5
  priority_95_: 0.5
  priority_96_: 0.5
  priority_97_: 0.5
  priority_98_: 0.5
  priority_99_: 0.5
  priority_100_: 0.5
  priority_101_: 0.5
  priority_102_: 0.5
  priority_103_: 0.5
  priority_104_: 0.5
  priority_105_: 0.5
  priority_106_: 0.5
  priority_107_: 0.5
  priority_108_: 0.5
  priority_109_: 0.5
  priority_110_: 0.5
  priority_111_: 0.5
  priority_112_: 0.5
  priority_113_: 0.5
  priority_114_: 0.5
  priority_115_: 0.5
  priority_116_: 0.5
  priority_117_: 0.5
  priority_118_: 0.5
  priority_119_: 0.5
  priority_120_: 0.5
  priority_121_: 0.5
  priority_122_: 0.5
  priority_123_: 0.5
  priority_124_: 0.5
  priority_125_: 0.5
  priority_126_: 0.5
  priority_127_: 0.5
  req_0_: 0.5
  req_1_: 0.5
  req_2_: 0.5
  req_3_: 0.5
  req_4_: 0.5
  req_5_: 0.5
  req_6_: 0.5
  req_7_: 0.5
  req_8_: 0.5
  req_9_: 0.5
  req_10_: 0.5
  req_11_: 0.5
  req_12_: 0.5
  req_13_: 0.5
  req_14_: 0.5
  req_15_: 0.5
  req_16_: 0.5
  req_17_: 0.5
  req_18_: 0.5
  req_19_: 0.5
  req_20_: 0.5
  req_21_: 0.5
  req_22_: 0.5
  req_23_: 0.5
  req_24_: 0.5
  req_25_: 0.5
  req_26_: 0.5
  req_27_: 0.5
  req_28_: 0.5
  req_29_: 0.5
  req_30_: 0.5
  req_31_: 0.5
  req_32_: 0.5
  req_33_: 0.5
  req_34_: 0.5
  req_35_: 0.5
  req_36_: 0.5
  req_37_: 0.5
  req_38_: 0.5
  req_39_: 0.5
  req_40_: 0.5
  req_41_: 0.5
  req_42_: 0.5
  req_43_: 0.5
  req_44_: 0.5
  req_45_: 0.5
  req_46_: 0.5
  req_47_: 0.5
  req_48_: 0.5
  req_49_: 0.5
  req_50_: 0.5
  req_51_: 0.5
  req_52_: 0.5
  req_53_: 0.5
  req_54_: 0.5
  req_55_: 0.5
  req_56_: 0.5
  req_57_: 0.5
  req_58_: 0.5
  req_59_: 0.5
  req_60_: 0.5
  req_61_: 0.5
  req_62_: 0.5
  req_63_: 0.5
  req_64_: 0.5
  req_65_: 0.5
  req_66_: 0.5
  req_67_: 0.5
  req_68_: 0.5
  req_69_: 0.5
  req_70_: 0.5
  req_71_: 0.5
  req_72_: 0.5
  req_73_: 0.5
  req_74_: 0.5
  req_75_: 0.5
  req_76_: 0.5
  req_77_: 0.5
  req_78_: 0.5
  req_79_: 0.5
  req_80_: 0.5
  req_81_: 0.5
  req_82_: 0.5
  req_83_: 0.5
  req_84_: 0.5
  req_85_: 0.5
  req_86_: 0.5
  req_87_: 0.5
  req_88_: 0.5
  req_89_: 0.5
  req_90_: 0.5
  req_91_: 0.5
  req_92_: 0.5
  req_93_: 0.5
  req_94_: 0.5
  req_95_: 0.5
  req_96_: 0.5
  req_97_: 0.5
  req_98_: 0.5
  req_99_: 0.5
  req_100_: 0.5
  req_101_: 0.5
  req_102_: 0.5
  req_103_: 0.5
  req_104_: 0.5
  req_105_: 0.5
  req_106_: 0.5
  req_107_: 0.5
  req_108_: 0.5
  req_109_: 0.5
  req_110_: 0.5
  req_111_: 0.5
  req_112_: 0.5
  req_113_: 0.5
  req_114_: 0.5
  req_115_: 0.5
  req_116_: 0.5
  req_117_: 0.5
  req_118_: 0.5
  req_119_: 0.5
  req_120_: 0.5
  req_121_: 0.5
  req_122_: 0.5
  req_123_: 0.5
  req_124_: 0.5
  req_125_: 0.5
  req_126_: 0.5
  req_127_: 0.5
