libs:
- asap7sc7p5t_SIMPLE_RVT_TT_nldm_211120
- asap7sc7p5t_AO_RVT_TT_nldm_211120
- asap7sc7p5t_INVBUF_RVT_TT_nldm_220122
- asap7sc7p5t_OA_RVT_TT_nldm_211120
- asap7sc7p5t_SEQ_RVT_TT_nldm_220123
- manual
port_prefixes:
  input:
  - .A
  - .B
  - .C
  - .D
  - .E
  - .CI
  - .H
  output:
  - .Y
  - .QN
  - .L
  - .SN
  - .CON
external_sp_inputs_spec:
  totalcoeffs_0_: 0.65
  totalcoeffs_1_: 0.25
  totalcoeffs_2_: 0.6
  totalcoeffs_3_: 0.45
  totalcoeffs_4_: 0.2
  ctable_0_: 0.45
  ctable_1_: 0.4
  ctable_2_: 0.45
  trailingones_0_: 0.55
  trailingones_1_: 0.5
