libs:
- asap7sc7p5t_SIMPLE_RVT_TT_nldm_211120
- asap7sc7p5t_AO_RVT_TT_nldm_211120
- asap7sc7p5t_INVBUF_RVT_TT_nldm_220122
- asap7sc7p5t_OA_RVT_TT_nldm_211120
- asap7sc7p5t_SEQ_RVT_TT_nldm_220123
- manual
port_prefixes:
  input:
  - .A
  - .B
  - .C
  - .D
  - .E
  - .CI
  - .H
  output:
  - .Y
  - .QN
  - .L
  - .SN
  - .CON
external_sp_inputs_spec:
  count_0_: 0.65
  count_1_: 0.25
  count_2_: 0.6
  count_3_: 0.45
  count_4_: 0.2
  count_5_: 0.45
  count_6_: 0.4
  count_7_: 0.45
